// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package userview

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/aph138/shop/server/web/layout"
import "github.com/aph138/shop/shared"

func Cart() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container mx-auto p-4\"><h1 class=\"text-2xl font-bold mb-4\">Cart</h1><div class=\"shadow-md rounded-lg p-4\"><table class=\"w-full\"><thead><tr class=\"border-b\"><th class=\"py-2 text-left\">Product</th><th class=\"py-2 text-left\">Price</th><th class=\"py-2 text-left\">Quantity</th><th class=\"py-2 text-left\">Total</th><th class=\"py-2 text-left\"></th></tr></thead> <tbody><tr class=\"border-b bg-gray-100\"><td class=\"py-2\"><div class=\"flex items-center\"><img src=\"\" class=\"w-16 h-16 object-cover rounded mr-4\"><div><p class=\"font-bold\">Name</p><p class=\"text-gray-500\">Description</p></div></div></td><td class=\"py-2\">Price</td><td class=\"py-2\"><input type=\"number\" class=\"border p-1 w-16\" value=\"1\" min=\"1\"></td><td class=\"py-2\">Total</td><td class=\"py-2\"><button class=\"text-red-500\">Remove</button></td></tr></tbody></table></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.Main("Cart", shared.User{}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
