FROM golang

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY ./server/ ./
RUN mkdir server
RUN mv ./handler ./server/handler
COPY ./pkg/ ./pkg
COPY ./shared ./shared
COPY ./api/ ./api/
COPY /server/web/ ./server/web
COPY jwt.ed jwt.ed.pub ./
#RUN go build -o main

EXPOSE 9000

#CMD [ "./main" ]
CMD [ "go", "run", "." ]